name: CI Pipeline

# Ce workflow s'exécute à chaque fois qu'un push ou une pull request est réalisé sur la branche principale
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code de la branche
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Python et les dépendances
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install colorama pytest

      # Exécuter les tests unitaires avec pytest
      - name: Run tests
        run: pytest

      # Sauvegarder les résultats des tests
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: ./test-results/
